# Resolve the version-specific People design-level fields from the target IDD.
people__field_names <- function(ep) {
    stats::setNames(
        vapply(
            5:7,
            function(field) conv__idd_field_name(ep, "People", field),
            character(1L)
        ),
        c("number", "per_area", "area_per_person")
    )
}

# ROOM.TYPE -> ROOM_TYPE_DATA occupant fields -> People. The outdoor-air field
# is handled separately by outdoor_air__convert() so People remains focused on
# internal sensible and latent heat gains.
people__convert <- function(dest, ep, people_heat = "constant") {
    people_heat <- match.arg(
        people_heat,
        c("constant", "temperature_dependent")
    )
    if (!internal_gains__has_room_type_data(dest)) {
        return(NULL)
    }

    # NOTE: In DeST, the dehumidification load is calculated by the humidity
    # generated by people multiplied by the latent heat of vaporization (2500
    # kJ/kg, a fixed value). In EnergyPlus, the total heat generated by people
    # is input and latent heat is calculated from the Sensible Heat Fraction.
    # ROOM_TYPE_DATA stores the standard 68/109/184 g/h values despite its old
    # Access field comment saying kg/h; Calload serializes those integers
    # unchanged. Convert g/h to W with 2.5 kJ/g before adding sensible heat.
    people <- DBI::dbGetQuery(
        dest,
        "
        SELECT
            R.ID               AS ID,
            R.NAME || ' People' AS NAME,
            R.ID               AS ROOM_ID,
            R.NAME             AS ROOM_NAME,
            R.TYPE             AS ROOM_TYPE_ID,
            T.ID               AS ROOM_TYPE_DATA_ID,
            T.O_SCHEDULE       AS SCHEDULE_ID,
            S.NAME             AS SCHEDULE_NAME,
            T.O_DIST_MODE      AS DIST_MODE_ID,
            T.O_PER_AREA       AS CALCULATION_BASIS,
            CASE WHEN T.O_MAXNUMBER > 0 OR T.O_MINNUMBER > 0
                THEN 1 ELSE 0 END AS ACTIVE,
            CASE
                WHEN T.O_PER_AREA = 1 THEN 'People/Area'
                ELSE 'People'
            END                AS METHOD,
            CASE
                WHEN T.O_PER_AREA != 1 THEN T.O_MAXNUMBER
                ELSE NULL
            END                AS NUMBER_OF_PEOPLE,
            CASE
                WHEN T.O_PER_AREA = 1 THEN T.O_MAXNUMBER
                ELSE NULL
            END                AS PEOPLE_PER_AREA,
            CASE
                WHEN T.O_PER_AREA != 1 THEN T.O_MINNUMBER
                ELSE NULL
            END                AS MIN_NUMBER_OF_PEOPLE,
            CASE
                WHEN T.O_PER_AREA = 1 THEN T.O_MINNUMBER
                ELSE NULL
            END                AS MIN_PEOPLE_PER_AREA,
            T.O_HEAT_PER_PERSON + T.O_DAMP_PER_PERSON * 2.5 / 3.6
                               AS ACTIVITY_LEVEL,
            T.O_HEAT_PER_PERSON AS BASE_SENSIBLE_HEAT,
            CASE WHEN T.O_HEAT_PER_PERSON + T.O_DAMP_PER_PERSON = 0
                THEN 1 ELSE T.O_HEAT_PER_PERSON /
                (T.O_HEAT_PER_PERSON + T.O_DAMP_PER_PERSON * 2.5 / 3.6) END
                               AS SENSIBLE_HEAT_FRACTION,
            ROUND(1.0 - DM.DIST_AIR, 3)
                               AS FRACTION_RADIANT,
            T.O_MIN_REQUIRE_FRESH_AIR
                               AS MIN_FRESH_AIR
        FROM ROOM R
        LEFT JOIN ROOM_TYPE_DATA T
        ON R.TYPE = T.ID
        LEFT JOIN SCHEDULE_YEAR S
        ON T.O_SCHEDULE = S.SCHEDULE_ID
        LEFT JOIN DIST_MODE DM
        ON T.O_DIST_MODE = DM.DIST_MODE_ID
        ORDER BY R.ID
        "
    )
    data.table::setDT(people)
    internal_gains__assert_references(people, "occupant")
    people <- people[ACTIVE != 0L]
    if (nrow(people) == 0L) {
        return(NULL)
    }
    dt_force_numeric(
        people,
        c(
            "NUMBER_OF_PEOPLE",
            "PEOPLE_PER_AREA",
            "MIN_NUMBER_OF_PEOPLE",
            "MIN_PEOPLE_PER_AREA",
            "ACTIVITY_LEVEL",
            "BASE_SENSIBLE_HEAT",
            "SENSIBLE_HEAT_FRACTION",
            "FRACTION_RADIANT",
            "MIN_FRESH_AIR"
        )
    )
    data.table::set(
        people,
        NULL,
        "ACTIVITY_SCHEDULE_NAME",
        sprintf("Activity Level %.2f W", people$ACTIVITY_LEVEL)
    )

    activity <- unique(people[, .(ACTIVITY_SCHEDULE_NAME, ACTIVITY_LEVEL)])
    has_min <- any(
        internal_gains__has_positive_minimum(people$MIN_NUMBER_OF_PEOPLE) |
            internal_gains__has_positive_minimum(people$MIN_PEOPLE_PER_AREA)
    )

    # NOTE: In DeST, the actual people number is calculated via:
    # min_val + sch_val * (max_val - min_val)
    #
    # EnergyPlus People objects multiply the design level by a schedule. When
    # the DeST minimum is non-zero, represent the same profile with two People
    # objects: a constant minimum object plus a scheduled (max - min) object.
    always_on <- "Always On - DeST Minimum People"
    zone_field_name <- internal_gains__zone_field_name(ep, "People")
    field_names <- people__field_names(ep)
    people_objects <- unlist(
        lapply(seq_len(nrow(people)), function(i) {
            people__values(
                people,
                i,
                always_on,
                zone_field_name,
                field_names
            )
        }),
        recursive = FALSE
    )

    parts <- list(
        activity = conv__add(
            dest,
            ep,
            # TODO: handle the case when a generated activity-level schedule
            #       name already exists in the converted model.
            "Schedule:Constant" := list(
                name = activity$ACTIVITY_SCHEDULE_NAME,
                schedule_type_limits_name = NULL,
                hourly_value = activity$ACTIVITY_LEVEL
            )
        )
    )

    if (has_min) {
        parts$minimum_schedule <- internal_gains__always_on(
            dest,
            ep,
            always_on
        )
    }

    # NOTE: In EnergyPlus, the people activity level can be changed via
    # schedules. However, in DeST, it is a fixed value. So here we create a
    # constant activity-level schedule for each distinct activity level.
    parts$people <- conv__add_objects(dest, ep, "People", people_objects)
    # The bshell execution switch is absent from the source database. Preserve
    # the caller's choice in the saved People objects as well as the API call.
    data.table::set(
        parts$people$object,
        NULL,
        "comment",
        rep(
            list(paste0("DeST people_heat mode: ", people_heat)),
            nrow(parts$people$object)
        )
    )
    if (people_heat == "temperature_dependent") {
        parts$temperature <- people__temperature(
            dest,
            ep,
            people
        )
    }

    out <- conv__combine_outputs(parts, table = people)
    attr(out, "sources") <- people__source_specs(
        dest,
        people,
        people_objects,
        field_names[["number"]],
        field_names[["per_area"]],
        people_heat
    )
    out
}

# Generate the native sensible-heat relation in one place for both the people
# correction and any subsequent redistribution of that same sensible heat.
people__sensible_lines <- function(heat, temperature, variable) {
    c(
        sprintf(
            "SET %s = %.17g + 5.536 * (26 - %s)",
            variable,
            heat,
            temperature
        ),
        sprintf("SET %s = @MAX 0 %s", variable, variable)
    )
}

# Preserve the native previous-temperature sensible source while leaving the
# independently represented People count and moisture input unchanged. Native
# hourly equipment replay and changing-occupancy free-float checks establish
# the source rule; radiant recipient fractions still follow EnergyPlus.
people__temperature <- function(dest, ep, people) {
    if (
        numeric_version(as.character(ep$version())) < numeric_version("9.1.0")
    ) {
        stop(
            "Temperature-dependent people heat requires EnergyPlus 9.1.0 or newer.",
            call. = FALSE
        )
    }
    if (
        any(
            !is.finite(people$BASE_SENSIBLE_HEAT) |
                people$BASE_SENSIBLE_HEAT < 0
        )
    ) {
        stop(
            "Temperature-dependent people heat requires non-negative finite sensible inputs.",
            call. = FALSE
        )
    }
    classes <- c(
        "OtherEquipment",
        "EnergyManagementSystem:Sensor",
        "EnergyManagementSystem:InternalVariable",
        "EnergyManagementSystem:Actuator",
        "EnergyManagementSystem:Program",
        "EnergyManagementSystem:ProgramCallingManager"
    )
    values <- stats::setNames(lapply(classes, function(class) list()), classes)
    always_on <- "Always On - DeST People Temperature"
    zone_field <- conv__idd_field_name(ep, "OtherEquipment", 3L)
    for (i in seq_len(nrow(people))) {
        prefix <- paste0("DeST_People_T_", i)
        name <- paste(people$NAME[[i]], "Temperature Correction")
        per_area <- people$CALCULATION_BASIS[[i]] == 1L
        maximum <- if (per_area) {
            people$PEOPLE_PER_AREA[[i]]
        } else {
            people$NUMBER_OF_PEOPLE[[i]]
        }
        minimum <- internal_gains__zero_if_na(
            if (per_area) {
                people$MIN_PEOPLE_PER_AREA[[i]]
            } else {
                people$MIN_NUMBER_OF_PEOPLE[[i]]
            }
        )
        source <- list(
            name = name,
            fuel_type = "None",
            schedule_name = always_on,
            design_level_calculation_method = "EquipmentLevel",
            design_level = 0,
            fraction_latent = 0,
            fraction_radiant = people$FRACTION_RADIANT[[i]],
            fraction_lost = 0,
            end_use_subcategory = "DeST People Temperature Correction"
        )
        source[[zone_field]] <- people$ROOM_NAME[[i]]
        values$OtherEquipment <- c(values$OtherEquipment, list(source))
        values[["EnergyManagementSystem:Sensor"]] <- c(
            values[["EnergyManagementSystem:Sensor"]],
            list(
                list(
                    name = paste0(prefix, "_Temperature"),
                    output_variable_or_output_meter_index_key_name = people$ROOM_NAME[[
                        i
                    ]],
                    output_variable_or_output_meter_name = "Zone Mean Air Temperature"
                ),
                list(
                    name = paste0(prefix, "_Schedule"),
                    output_variable_or_output_meter_index_key_name = people$SCHEDULE_NAME[[
                        i
                    ]],
                    output_variable_or_output_meter_name = "Schedule Value"
                )
            )
        )
        if (per_area) {
            values[["EnergyManagementSystem:InternalVariable"]] <- c(
                values[["EnergyManagementSystem:InternalVariable"]],
                list(list(
                    name = paste0(prefix, "_Area"),
                    internal_data_index_key_name = people$ROOM_NAME[[i]],
                    internal_data_type = "Zone Floor Area"
                ))
            )
        }
        values[["EnergyManagementSystem:Actuator"]] <- c(
            values[["EnergyManagementSystem:Actuator"]],
            list(list(
                name = paste0(prefix, "_Power"),
                actuated_component_unique_name = name,
                actuated_component_type = "OtherEquipment",
                actuated_component_control_type = "Power Level"
            ))
        )
        # Apply minimum plus scheduled range once, before the zone multiplier.
        # Clamp the total native sensible power before subtracting the existing
        # constant People contribution, so high-temperature correction can be negative.
        lines <- c(
            sprintf(
                "SET Count = %.17g + %.17g * %s_Schedule",
                minimum,
                maximum - minimum,
                prefix
            ),
            if (per_area) sprintf("SET Count = Count * %s_Area", prefix),
            people__sensible_lines(
                people$BASE_SENSIBLE_HEAT[[i]],
                paste0(prefix, "_Temperature"),
                "Sensible"
            ),
            sprintf(
                "SET %s_Power = (Sensible - %.17g) * Count",
                prefix,
                people$BASE_SENSIBLE_HEAT[[i]]
            )
        )
        fields <- vapply(
            seq_along(lines) + 1L,
            function(field) {
                conv__idd_field_name(
                    ep,
                    "EnergyManagementSystem:Program",
                    field
                )
            },
            character(1L)
        )
        values[["EnergyManagementSystem:Program"]] <- c(
            values[["EnergyManagementSystem:Program"]],
            list(c(
                list(name = paste0(prefix, "_Control")),
                stats::setNames(as.list(lines), fields)
            ))
        )
        # Gains are consumed during heat-balance initialization. Calling this
        # before the predictor leaves an extra, experimentally confirmed lag.
        values[["EnergyManagementSystem:ProgramCallingManager"]] <- c(
            values[["EnergyManagementSystem:ProgramCallingManager"]],
            list(list(
                name = paste0(prefix, "_Manager"),
                energyplus_model_calling_point = "BeginZoneTimestepBeforeInitHeatBalance",
                program_name_1 = paste0(prefix, "_Control")
            ))
        )
    }
    conv__combine_outputs(c(
        list(internal_gains__always_on(dest, ep, always_on)),
        lapply(classes, function(class) {
            conv__add_objects(dest, ep, class, values[[class]])
        })
    ))
}

# Build the scheduled and minimum People objects using the source count basis.
people__values <- function(
    people,
    i,
    always_on,
    zone_field_name = "Zone or ZoneList or Space or SpaceList Name",
    field_names = c(
        number = "number_of_people",
        per_area = "people_per_floor_area",
        area_per_person = "floor_area_per_person"
    )
) {
    if (people$METHOD[[i]] == "People") {
        max_value <- people$NUMBER_OF_PEOPLE[[i]]
        min_value <- people$MIN_NUMBER_OF_PEOPLE[[i]]
        field <- field_names[["number"]]
    } else {
        max_value <- people$PEOPLE_PER_AREA[[i]]
        min_value <- people$MIN_PEOPLE_PER_AREA[[i]]
        field <- field_names[["per_area"]]
    }

    value_factory <- function(gain, row, name, schedule) {
        people__value(
            gain,
            row,
            name,
            schedule,
            zone_field_name,
            field_names
        )
    }
    internal_gains__split_minimum(
        people,
        i,
        max_value,
        min_value,
        field,
        always_on,
        value_factory
    )
}

# Describe one People object without changing its source heat fractions.
people__value <- function(
    people,
    i,
    name,
    schedule,
    zone_field_name,
    field_names
) {
    value <- list(
        name = name,
        number_of_people_schedule_name = schedule,
        number_of_people_calculation_method = people$METHOD[[i]],
        fraction_radiant = people$FRACTION_RADIANT[[i]],
        sensible_heat_fraction = people$SENSIBLE_HEAT_FRACTION[[i]],
        activity_level_schedule_name = people$ACTIVITY_SCHEDULE_NAME[[i]]
    )
    value[[zone_field_name]] <- people$ROOM_NAME[[i]]
    for (field in field_names) {
        value[[field]] <- NULL
    }
    value
}

# Attach People heat metadata to the same object inventory used for conversion.
people__source_specs <- function(
    dest,
    people,
    values,
    total_field,
    area_field,
    people_heat
) {
    # The temperature correction belongs to the whole source count, including
    # both its always-on minimum and its scheduled increment.
    decorate <- function(item, row) {
        item$sensible_heat <- people$BASE_SENSIBLE_HEAT[[row]]
        item$temperature_dependent <- people_heat == "temperature_dependent"
        if (item$temperature_dependent) {
            item$companion_objects <- paste(
                people$NAME[[row]],
                "Temperature Correction"
            )
        }
        item
    }
    internal_gains__source_specs(
        dest,
        people,
        values,
        "people",
        total_field,
        area_field,
        "number_of_people_schedule_name",
        decorate
    )
}
