destep_conv_internal_gains <- function(dest, ep) {
    conv <- Filter(Negate(is.null), list(
        OCCUPANT_GAINS = destep_conv_people(dest, ep),
        LIGHT_GAINS = destep_conv_lights(dest, ep),
        EQUIPMENT_GAINS = destep_conv_electric_equipment(dest, ep)
    ))

    destep_combine_outputs(conv)
}

# OCCUPANT_GAINS -> People
# TODO: Map OCCUPANT_GAINS$MIN_REQUIRE_FRESH_AIR to
#       DesignSpecification:OutdoorAir once ventilation conversion is supported.
destep_conv_people <- function(dest, ep) {
    if (!destep_has_rows(dest, "OCCUPANT_GAINS")) return(NULL)

    # NOTE: In DeST, the dehumidification load is calculated by the humidity
    # generated by people multiplied by the latent heat of vaporization (2500
    # kJ/kg, a fixed value). In EnergyPlus, the total heat generated by people
    # is input and latent heat is calculated from the Sensible Heat Fraction.
    people <- DBI::dbGetQuery(
        dest,
        "
        SELECT
            O.GAIN_ID          AS ID,
            O.NAME             AS NAME,
            R.NAME             AS ROOM_NAME,
            S.NAME             AS SCHEDULE_NAME,
            CASE
                WHEN O.PER_AREA = 1 THEN 'People/Area'
                ELSE 'People'
            END                AS METHOD,
            CASE
                WHEN O.PER_AREA != 1 THEN O.MAXNUMBER
                ELSE NULL
            END                AS NUMBER_OF_PEOPLE,
            CASE
                WHEN O.PER_AREA = 1 THEN O.MAXNUMBER
                ELSE NULL
            END                AS PEOPLE_PER_AREA,
            CASE
                WHEN O.PER_AREA != 1 THEN O.MINNUMBER
                ELSE NULL
            END                AS MIN_NUMBER_OF_PEOPLE,
            CASE
                WHEN O.PER_AREA = 1 THEN O.MINNUMBER
                ELSE NULL
            END                AS MIN_PEOPLE_PER_AREA,
            ROUND(O.HEAT_PER_PERSON + O.DAMP_PER_PERSON * 2500 / 3.6, 2)
                               AS ACTIVITY_LEVEL,
            ROUND(
                O.HEAT_PER_PERSON /
                    (O.HEAT_PER_PERSON + O.DAMP_PER_PERSON * 2500 / 3.6),
                2
            )                  AS SENSIBLE_HEAT_FRACTION,
            ROUND(1.0 - DM.DIST_AIR, 3)
                               AS FRACTION_RADIANT,
            O.MIN_REQUIRE_FRESH_AIR
                               AS MIN_FRESH_AIR
        FROM OCCUPANT_GAINS O
        LEFT JOIN ROOM R
        ON O.OF_ROOM = R.ID
        LEFT JOIN SCHEDULE_YEAR S
        ON O.SCHEDULE = S.SCHEDULE_ID
        LEFT JOIN DIST_MODE DM
        ON O.DIST_MODE = DM.DIST_MODE_ID
        "
    )
    data.table::setDT(people)
    destep_force_numeric(people, c(
        "NUMBER_OF_PEOPLE", "PEOPLE_PER_AREA", "MIN_NUMBER_OF_PEOPLE",
        "MIN_PEOPLE_PER_AREA", "ACTIVITY_LEVEL", "SENSIBLE_HEAT_FRACTION",
        "FRACTION_RADIANT", "MIN_FRESH_AIR"
    ))
    data.table::set(
        people, NULL, "ACTIVITY_SCHEDULE_NAME",
        sprintf("Activity Level %.2f W", people$ACTIVITY_LEVEL)
    )

    activity <- unique(people[, .(ACTIVITY_SCHEDULE_NAME, ACTIVITY_LEVEL)])
    has_min <- any(
        destep_has_positive_minimum(people$MIN_NUMBER_OF_PEOPLE) |
            destep_has_positive_minimum(people$MIN_PEOPLE_PER_AREA)
    )

    # NOTE: In DeST, the actual people number is calculated via:
    # min_val + sch_val * (max_val - min_val)
    #
    # EnergyPlus People objects multiply the design level by a schedule. When
    # the DeST minimum is non-zero, represent the same profile with two People
    # objects: a constant minimum object plus a scheduled (max - min) object.
    always_on <- "Always On - DeST Minimum People"
    people_objects <- unlist(lapply(seq_len(nrow(people)), function(i) {
        destep_people_values(people, i, always_on)
    }), recursive = FALSE)

    parts <- list(
        activity = destep_add(
            dest, ep,
            # TODO: handle the case when a generated activity-level schedule
            #       name already exists in the converted model.
            "Schedule:Constant" := list(
                name = activity$ACTIVITY_SCHEDULE_NAME,
                schedule_type_limits_name = NULL,
                hourly_value = activity$ACTIVITY_LEVEL
            )
        )
    )

    if (has_min) {
        parts$minimum_schedule <- destep_internal_gain_always_on(
            dest, ep, always_on
        )
    }

    # NOTE: In EnergyPlus, the people activity level can be changed via
    # schedules. However, in DeST, it is a fixed value. So here we create a
    # constant activity-level schedule for each distinct activity level.
    parts$people <- eval(as.call(c(
        destep_add, dest, ep,
        lapply(people_objects, function(val) bquote("People" := .(val)))
    )))

    destep_combine_outputs(parts, table = people)
}

destep_people_values <- function(people, i, always_on) {
    if (people$METHOD[[i]] == "People") {
        max_value <- people$NUMBER_OF_PEOPLE[[i]]
        min_value <- destep_zero_if_na(people$MIN_NUMBER_OF_PEOPLE[[i]])
        field <- "number_of_people"
    } else {
        max_value <- people$PEOPLE_PER_AREA[[i]]
        min_value <- destep_zero_if_na(people$MIN_PEOPLE_PER_AREA[[i]])
        field <- "people_per_floor_area"
    }

    variable_value <- max_value - min_value

    out <- list()
    if (variable_value > 0 || min_value <= 0) {
        val <- destep_people_value(people, i, people$NAME[[i]], people$SCHEDULE_NAME[[i]])
        val[[field]] <- variable_value
        out <- c(out, list(val))
    }

    if (min_value > 0) {
        val <- destep_people_value(
            people, i, paste(people$NAME[[i]], "Minimum"), always_on
        )
        val[[field]] <- min_value
        out <- c(out, list(val))
    }

    out
}

destep_people_value <- function(people, i, name, schedule) {
    # NOTE: Older EnergyPlus versions used a shorter People field 2 name before
    # the Space concept was introduced. eplusr accepts the current canonical
    # field name for supported IDDs, so keep named fields instead of positional
    # loading here.
    list(
        name = name,
        zone_or_zonelist_or_space_or_spacelist_name = people$ROOM_NAME[[i]],
        number_of_people_schedule_name = schedule,
        number_of_people_calculation_method = people$METHOD[[i]],
        number_of_people = NULL,
        people_per_floor_area = NULL,
        floor_area_per_person = NULL,
        fraction_radiant = people$FRACTION_RADIANT[[i]],
        sensible_heat_fraction = people$SENSIBLE_HEAT_FRACTION[[i]],
        activity_level_schedule_name = people$ACTIVITY_SCHEDULE_NAME[[i]]
    )
}

# LIGHT_GAINS -> Lights
destep_conv_lights <- function(dest, ep) {
    if (!destep_has_rows(dest, "LIGHT_GAINS")) return(NULL)

    lights <- DBI::dbGetQuery(
        dest,
        "
        SELECT
            L.GAIN_ID        AS ID,
            L.NAME           AS NAME,
            R.NAME           AS ROOM_NAME,
            S.NAME           AS SCHEDULE_NAME,
            CASE
                WHEN L.PER_AREA = 1 THEN 'Watts/Area'
                ELSE 'LightingLevel'
            END              AS METHOD,
            CASE
                WHEN L.PER_AREA != 1 THEN L.MAXPOWER
                ELSE NULL
            END              AS LIGHTING_LEVEL,
            CASE
                WHEN L.PER_AREA = 1 THEN L.MAXPOWER
                ELSE NULL
            END              AS WATTS_PER_AREA,
            CASE
                WHEN L.PER_AREA != 1 THEN L.MINPOWER
                ELSE NULL
            END              AS MIN_LIGHTING_LEVEL,
            CASE
                WHEN L.PER_AREA = 1 THEN L.MINPOWER
                ELSE NULL
            END              AS MIN_WATTS_PER_AREA,
            ROUND(1.0 - DM.DIST_AIR, 3)
                             AS FRACTION_RADIANT,
            L.HEAT_RATE      AS FRACTION_REPLACEABLE
        FROM LIGHT_GAINS L
        LEFT JOIN ROOM R
        ON L.OF_ROOM = R.ID
        LEFT JOIN SCHEDULE_YEAR S
        ON L.SCHEDULE = S.SCHEDULE_ID
        LEFT JOIN DIST_MODE DM
        ON L.DIST_MODE = DM.DIST_MODE_ID
        "
    )
    data.table::setDT(lights)
    destep_force_numeric(lights, c(
        "LIGHTING_LEVEL", "WATTS_PER_AREA", "MIN_LIGHTING_LEVEL",
        "MIN_WATTS_PER_AREA", "FRACTION_RADIANT", "FRACTION_REPLACEABLE"
    ))
    watts_per_area_field <- destep_idd_field_name(ep, "Lights", 6L)
    has_min <- any(
        destep_has_positive_minimum(lights$MIN_LIGHTING_LEVEL) |
            destep_has_positive_minimum(lights$MIN_WATTS_PER_AREA)
    )

    # DeST light gains use the same min + schedule * (max - min) pattern as
    # people. Use a constant minimum Lights object plus a scheduled variable
    # object when MINPOWER is non-zero.
    always_on <- "Always On - DeST Minimum Lights"
    light_objects <- unlist(lapply(seq_len(nrow(lights)), function(i) {
        destep_light_values(lights, i, watts_per_area_field, always_on)
    }), recursive = FALSE)

    parts <- list()
    if (has_min) {
        parts$minimum_schedule <- destep_internal_gain_always_on(
            dest, ep,
            always_on
        )
    }

    parts$lights <- eval(as.call(c(
        destep_add, dest, ep,
        lapply(light_objects, function(val) bquote("Lights" := .(val)))
    )))

    destep_combine_outputs(parts, table = lights)
}

destep_light_values <- function(lights, i, watts_per_area_field, always_on) {
    if (lights$METHOD[[i]] == "LightingLevel") {
        max_value <- lights$LIGHTING_LEVEL[[i]]
        min_value <- destep_zero_if_na(lights$MIN_LIGHTING_LEVEL[[i]])
        field <- "lighting_level"
    } else {
        max_value <- lights$WATTS_PER_AREA[[i]]
        min_value <- destep_zero_if_na(lights$MIN_WATTS_PER_AREA[[i]])
        field <- watts_per_area_field
    }

    variable_value <- max_value - min_value

    out <- list()
    if (variable_value > 0 || min_value <= 0) {
        val <- destep_light_value(lights, i, lights$NAME[[i]], lights$SCHEDULE_NAME[[i]])
        val[[field]] <- variable_value
        out <- c(out, list(val))
    }

    if (min_value > 0) {
        val <- destep_light_value(
            lights, i, paste(lights$NAME[[i]], "Minimum"), always_on
        )
        val[[field]] <- min_value
        out <- c(out, list(val))
    }

    out
}

destep_light_value <- function(lights, i, name, schedule) {
    list(
        name = name,
        zone_or_zonelist_or_space_or_spacelist_name = lights$ROOM_NAME[[i]],
        schedule_name = schedule,
        design_level_calculation_method = lights$METHOD[[i]],
        lighting_level = NULL,
        watts_per_person = NULL,
        return_air_fraction = 0,
        fraction_radiant = lights$FRACTION_RADIANT[[i]],
        fraction_visible = 0.2,
        fraction_replaceable = lights$FRACTION_REPLACEABLE[[i]],
        end_use_subcategory = "General"
    )
}

# EQUIPMENT_GAINS -> ElectricEquipment
destep_conv_electric_equipment <- function(dest, ep) {
    if (!destep_has_rows(dest, "EQUIPMENT_GAINS")) return(NULL)

    equipment <- DBI::dbGetQuery(
        dest,
        "
        SELECT
            E.GAIN_ID        AS ID,
            E.NAME           AS NAME,
            R.NAME           AS ROOM_NAME,
            S.NAME           AS SCHEDULE_NAME,
            CASE
                WHEN E.PER_AREA = 1 THEN 'Watts/Area'
                ELSE 'EquipmentLevel'
            END              AS METHOD,
            CASE
                WHEN E.PER_AREA != 1 THEN E.MAXPOWER
                ELSE NULL
            END              AS DESIGN_LEVEL,
            CASE
                WHEN E.PER_AREA = 1 THEN E.MAXPOWER
                ELSE NULL
            END              AS WATTS_PER_AREA,
            CASE
                WHEN E.PER_AREA != 1 THEN E.MINPOWER
                ELSE NULL
            END              AS MIN_DESIGN_LEVEL,
            CASE
                WHEN E.PER_AREA = 1 THEN E.MINPOWER
                ELSE NULL
            END              AS MIN_WATTS_PER_AREA,
            ROUND(1.0 - DM.DIST_AIR, 3)
                             AS FRACTION_RADIANT
        FROM EQUIPMENT_GAINS E
        LEFT JOIN ROOM R
        ON E.OF_ROOM = R.ID
        LEFT JOIN SCHEDULE_YEAR S
        ON E.SCHEDULE = S.SCHEDULE_ID
        LEFT JOIN DIST_MODE DM
        ON E.DIST_MODE = DM.DIST_MODE_ID
        "
    )
    data.table::setDT(equipment)
    destep_force_numeric(equipment, c(
        "DESIGN_LEVEL", "WATTS_PER_AREA", "MIN_DESIGN_LEVEL",
        "MIN_WATTS_PER_AREA", "FRACTION_RADIANT"
    ))
    watts_per_area_field <- destep_idd_field_name(ep, "ElectricEquipment", 6L)
    has_min <- any(
        destep_has_positive_minimum(equipment$MIN_DESIGN_LEVEL) |
            destep_has_positive_minimum(equipment$MIN_WATTS_PER_AREA)
    )

    # DeST equipment gains also store MINPOWER/MAXPOWER. Use the same
    # minimum-plus-variable representation as people and lights.
    always_on <- "Always On - DeST Minimum Equipment"
    equipment_objects <- unlist(lapply(seq_len(nrow(equipment)), function(i) {
        destep_equipment_values(equipment, i, watts_per_area_field, always_on)
    }), recursive = FALSE)

    parts <- list()
    if (has_min) {
        parts$minimum_schedule <- destep_internal_gain_always_on(
            dest, ep, always_on
        )
    }

    parts$equipment <- eval(as.call(c(
        destep_add, dest, ep,
        lapply(equipment_objects, function(val) bquote("ElectricEquipment" := .(val)))
    )))

    destep_combine_outputs(parts, table = equipment)
}

destep_equipment_values <- function(equipment, i, watts_per_area_field, always_on) {
    if (equipment$METHOD[[i]] == "EquipmentLevel") {
        max_value <- equipment$DESIGN_LEVEL[[i]]
        min_value <- destep_zero_if_na(equipment$MIN_DESIGN_LEVEL[[i]])
        field <- "design_level"
    } else {
        max_value <- equipment$WATTS_PER_AREA[[i]]
        min_value <- destep_zero_if_na(equipment$MIN_WATTS_PER_AREA[[i]])
        field <- watts_per_area_field
    }

    variable_value <- max_value - min_value

    out <- list()
    if (variable_value > 0 || min_value <= 0) {
        val <- destep_equipment_value(
            equipment, i, equipment$NAME[[i]], equipment$SCHEDULE_NAME[[i]]
        )
        val[[field]] <- variable_value
        out <- c(out, list(val))
    }

    if (min_value > 0) {
        val <- destep_equipment_value(
            equipment, i, paste(equipment$NAME[[i]], "Minimum"), always_on
        )
        val[[field]] <- min_value
        out <- c(out, list(val))
    }

    out
}

destep_equipment_value <- function(equipment, i, name, schedule) {
    list(
        name = name,
        zone_or_zonelist_or_space_or_spacelist_name = equipment$ROOM_NAME[[i]],
        schedule_name = schedule,
        design_level_calculation_method = equipment$METHOD[[i]],
        design_level = NULL,
        watts_per_person = NULL,
        fraction_latent = 0,
        fraction_radiant = equipment$FRACTION_RADIANT[[i]],
        fraction_lost = 0,
        end_use_subcategory = "General"
    )
}

destep_has_rows <- function(dest, table) {
    table %in% DBI::dbListTables(dest) &&
        DBI::dbGetQuery(dest, sprintf("SELECT COUNT(*) AS N FROM `%s`", table))$N > 0L
}

destep_force_numeric <- function(dt, cols) {
    for (col in cols) {
        data.table::set(dt, NULL, col, as.numeric(dt[[col]]))
    }
    invisible(dt)
}

destep_has_positive_minimum <- function(x) {
    !is.na(x) & x > 0
}

destep_zero_if_na <- function(x) {
    if (is.na(x)) 0 else x
}

destep_internal_gain_always_on <- function(dest, ep, name) {
    destep_add(
        dest, ep,
        "Schedule:Constant" := list(
            name = name,
            schedule_type_limits_name = NULL,
            hourly_value = 1
        )
    )
}

destep_combine_outputs <- function(outputs, table = NULL) {
    outputs <- Filter(Negate(is.null), outputs)
    if (length(outputs) == 0L) return(NULL)

    num_obj <- 0L
    for (i in seq_along(outputs)) {
        data.table::set(outputs[[i]]$object, NULL, "rleid", outputs[[i]]$object$rleid + num_obj)
        data.table::set(outputs[[i]]$value, NULL, "rleid", outputs[[i]]$value$rleid + num_obj)
        num_obj <- max(outputs[[i]]$object$rleid)
    }

    out <- list(
        object = data.table::rbindlist(lapply(outputs, .subset2, "object")),
        value = data.table::rbindlist(lapply(outputs, .subset2, "value"))
    )

    if (is.null(table)) {
        table <- data.table::rbindlist(
            lapply(names(outputs), function(name) {
                tbl <- attr(outputs[[name]], "table")
                if (is.null(tbl)) return(NULL)
                data.table::set(data.table::copy(tbl), NULL, "SOURCE_TABLE", name)
            }),
            fill = TRUE
        )
    }
    # Always attach the source table snapshot to the output in case it is useful
    # later for diagnostics or follow-up converters.
    attr(out, "table") <- table

    out
}
